### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by justinmoon** [timhall/svelte-apollo#35]
```
$ git clone git@github.com:timhall/svelte-apollo.git
$ cd svelte-apollo
$ npm i
$ npm run example
rollup v1.17.0
bundles src/main.js → public/bundle.js...
GraphQL server listening on localhost:4001
[!] Error: Could not resolve '../../' from src/App.svelte
Error: Could not resolve '../../' from src/App.svelte
    at error (/home/justin/dev/experiments/svelte-apollo/node_modules/rollup/dist/rollup.js:9408:30)
    at ModuleLoader.handleMissingImports (/home/justin/dev/experiments/svelte-apollo/node_modules/rollup/dist/rollup.js:16442:17)
    at ModuleLoader.<anonymous> (/home/justin/dev/experiments/svelte-apollo/node_modules/rollup/dist/rollup.js:16493:26)
    at Generator.next (<anonymous>)
    at fulfilled (/home/justin/dev/experiments/svelte-apollo/node_modules/rollup/dist/rollup.js:15466:28)

1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-apollo@0.3.0-beta.3 example:build: `cd example && rollup -c -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-apollo@0.3.0-beta.3 example:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/justin/.npm/_logs/2019-12-31T23_20_49_232Z-debug.log
ERROR: "example:build" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-apollo@0.3.0-beta.3 example: `run-p example:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-apollo@0.3.0-beta.3 example script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/justin/.npm/_logs/2019-12-31T23_20_49_321Z-debug.log
```

**Comment by jasonzhouu** [comment]
I have the problem

**Comment by lisabchina** [comment]
svelteApollo is not defined / when running the example
I also tried to create an alias in output.globals but still the same issue.

Could you please provide us with a real; **working** example , and steps to run it properly ?

Kindest regards

**Comment by frederikhors** [comment]
Hi all.

The example is working.

After:

```
$ git clone git@github.com:timhall/svelte-apollo.git
$ cd svelte-apollo
$ npm i
```

do a

```
$ npm run build
```

and then a

```
$ npm run example
```

**Comment by jasonzhouu** [comment]
@frederikhors Thank you for sharing your experience, but I still get an error when execute `npm run build`:
```
Error: Cannot find module './build/bindings/iltorb.node'
```

**Comment by frederikhors** [comment]
Your environment is the problem. Upgrade nodejs.

**Comment by lisabey33** [comment]
> Hi all.
> 
> The example is working.
> 
> After:
> 
> ```
> $ git clone https://github.com/timhall/svelte-apollo.git
> $ cd svelte-apollo
> $ npm i
> ```
> 
> do a
> 
> ```
> $ npm run build
> ```
> 
> and then a
> 
> ```
> $ npm run example
> ```

I do this on two different environment and get the following : main.js:8 Uncaught ReferenceError: svelteApollo is not defined

**Comment by jasonzhouu** [comment]
@frederikhors I have tried nodejs v13.5.0, which is the newest version on show on https://nodejs.org/en/

**Comment by frederikhors** [comment]
@jasonzhouu, still having problems?

If not please close this.

**Comment by ZerdoX-x** [comment]
I also can't run the example.
```js
import ApolloClient from 'apollo-boost'
import { setClient } from 'svelte-apollo'
const client = new ApolloClient({ uri: '...' })
setClient(client)
```
gives me `ReferenceError: ApolloClient is not defined` in browser after `npm run build` & `npm run start`
